### ISSUE TITLE
做成fabric模组

### ISSUE THREAD

**Issue by abwmocc** [myunco/LiteItemShow#5]
我的服务器是fabric1.20.4服务端,但我没有找到适配fabric的物品展示
知道我发现了这个,可它是一个插件
作者可不可以试着做一个mod,或者...寻求一下平替的方案
感谢!

**Comment by myunco** [comment]
模组和插件还是有不少差别的，我也没有编写过fabric mod，所以无能为力。
至于平替方案，我也不清楚有什么mod提供了这个功能。
